### ISSUE TITLE
"This constructor has been deprecated" when compiling.

### ISSUE THREAD

**Issue by thalpius** [zcgonvh/EfsPotato#1]
For those getting the following message when compiling using the command line:

`warning CS0618: 'System.IO.FileStream.FileStream(System.IntPtr,
        System.IO.FileAccess, bool)' is obsolete: 'This constructor has been deprecated.  Please use new
        FileStream(SafeFileHandle handle, FileAccess access) instead, and optionally make a new SafeFileHandle with
        ownsHandle=false if needed.  http://go.microsoft.com/fwlink/?linkid=14202'`

You can use the following command:

`csc.exe EfsPotato.cs -nowarn:1691,618`

**Comment by zcgonvh** [comment]
ahhh updated, thx.
