### ISSUE TITLE
operation timed out error

### ISSUE THREAD

**Issue by kt-mc** [zcgonvh/EfsPotato#3]
I'm doing some testing and tried to compile and run:

.\EfsPotato.exe whoami

and end up with a [x] operation timed out. message. 

Could you provide some context into why this might be?

**Comment by zcgonvh** [comment]
the “fake pipe” not accept a connection within 3000ms.
try another pipe like efsrpc/lsass.



------------------ Original ------------------
From: kt-mc ***@***.***&gt;
Date: Sun,May 15,2022 10:54 PM
To: zcgonvh/EfsPotato ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [zcgonvh/EfsPotato] operation timed out error (Issue #3)





 
I'm doing some testing and tried to compile and run:
 
.\EfsPotato.exe whoami
 
and end up with a [x] operation timed out. message.
 
Could you provide some context into why this might be?

**Comment by kt-mc** [comment]
If all pipe options available produce the same result, do you have any suggestions as to why?

**Comment by kt-mc** [comment]
most likely the target was patched. Do you know the last windows build that this would be effective against?
