### ISSUE TITLE
Error in construction

### ISSUE THREAD

**Issue by alhosane** [zcgonvh/EfsPotato#7]
EfsPotato.cs(429,156): error CS1026: ) expected
EfsPotato.cs(429,156): error CS1525: Invalid expression term ':'
EfsPotato.cs(429,158): error CS1002: ; expected
EfsPotato.cs(429,160): error CS1002: ; expected
EfsPotato.cs(429,160): error CS1525: Invalid expression term ')'

**Comment by zcgonvh** [comment]
updated.
