### ISSUE TITLE
Request for permission to add to HackTricks

### ISSUE THREAD

**Issue by sealldeveloper** [zcgonvh/EfsPotato#8]
Hello!

I wanted to ask if it was alright if I referenced this tool in a HackTricks pull request, as it says we need to 'ensure that you only upload content that you own or that have permission to share it from the original author (adding a reference to the author in the added text or at the end of the page you are modifying or both)'.

Would that be alright?

Thank you, 
- sealldev

**Comment by zcgonvh** [comment]
Yes, you can, reference it anywhere you need.

And, to be honest, I think this tip is obsolete. According to my tests, it doesn't work in many cases.

Just a suggestion, you can use [DCOMPotato](https://github.com/zcgonvh/DCOMPotato) or [GodPotato](https://github.com/BeichenDream/GodPotato) as better alternatives, they have more compatibility and still work with the latest versions.

DCOMPotato is my repository, you can also directly reference it, GodPotato belongs to another researcher, you may need to ask him for permission (if you need it).

Sorry for the late reply, good luck.

**Comment by sealldeveloper** [comment]
No issues on delay you were quite prompt, thank you!

I'll still reference it and DCOMPotato, I believe GodPotato is already referenced
